### ISSUE TITLE
Dados da empresa ao lado da logomarca do Boleto.

### ISSUE THREAD

**Issue by grupouweb** [gamuzabrasil/gamuza_slips-magento#1]
Olá Eneias,

Bom dia!

Conforme retorno do seu ticket pelo GIT referente a instalação do Shopline, estou instalando o seu módulo de boleto e deposito.

Do lado da logo, esta saindo o nome: Gamuza Slips - Baseado no projeto BoletoPHP. ao invés do nome da minha loja.

Editando o arquivo itau.php vejo as linhas:
// SEUS DADOS
$dadosboleto["identificacao"] = $identification; // "BoletoPhp - Código Aberto de Sistema de Boletos";
$dadosboleto["cpf_cnpj"] = $_POST ['company_taxvat']; // "";
$dadosboleto["endereco"] = $_POST ['company_address']; // "Coloque o endereço da sua empresa aqui";
$dadosboleto["cidade_uf"] = $_POST ['company_city_region']; // "Cidade / Estado";
$dadosboleto["cedente"] = $_POST ['company_name']; // "Coloque a Razão Social da sua empresa aqui";
Mas estes campos não aparecem para que eu possa colocar os dados da minha empresa na config do módulo no Admin.

Neste caso, como proceder para colocar o nome da empresa ao lado da logo?

Desde já agradeço sua atenção!

**Comment by eneiasramos** [comment]
Olá @grupouweb ! Tudo bem?

As informações da loja no boleto, são obtidas através das informações de loja, no painel administrativo do magento via menu:

Sistema -> Configuração -> Geral -> Informações sobre a Loja

O logo pode ser inserido através do menu:

Sistema -> Configuração -> Vendas -> Formas de Pagamento -> Boletos e Depósitos - Ajustes

Att,
