### ISSUE TITLE
Boleto emitido hoje mas com data e valor errado.

### ISSUE THREAD

**Issue by grupouweb** [gamuzabrasil/gamuza_slips-magento#2]
Boa noite Eneias,

Hoje um cliente efetuou a compra através de boleto bancário e o mesmo saiu com o valor e vencimento errados...

O date Time Zone esta configurado no PHP corretamente.

Eu zerei a loja para colocá-la em produção, mas pelo que posso perceber, o boleto aparenta estar sendo gerado com uma numeração da época do teste 00000050-6 sendo que o pedido é numero 00000052. Veja o anexo.

![captura de tela 2016-12-05 as 20 14 17](https://cloud.githubusercontent.com/assets/11443360/20904987/137e7ca2-bb29-11e6-8237-ae3cb3037fce.png)

É possível sincronizar o numero do pedido com o numero do boleto para sanar o erro?

Grato pela atenção!

**Comment by eneiasramos** [comment]
Olá @grupouweb ! Tudo bem?

Qual a URL da sua loja?

Att,

**Comment by grupouweb** [comment]
Olá Eneias,
www.planetapc.com.br

**Comment by eneiasramos** [comment]
Olá @grupouweb ! Tudo bem?

Nesse caso, você precisa ajustar o valor da sua tabela eav_entity_store com os número do último pedido. Em caso de limpeza dos dados da loja, esses parâmetros devem ser ajustados novamente.

Att,
