### ISSUE TITLE
Linhas com erro após emitir boleto.

### ISSUE THREAD

**Issue by grupouweb** [gamuzabrasil/gamuza_slips-magento#3]
Olá Eneias,
Boa noite!

Fui emitir um boleto teste aqui na minha loja e retornou os erros:

================================
Warning: strtotime(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /home/planeta/public_html/skin/gamuza/slips/itau.php on line 45

Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /home/planeta/public_html/skin/gamuza/slips/itau.php on line 45

Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /home/planeta/public_html/skin/gamuza/slips/itau.php on line 53

Warning: date(): It is not safe to rely on the system's timezone settings. You are *required* to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected the timezone 'UTC' for now, but please set date.timezone to select your timezone. in /home/planeta/public_html/skin/gamuza/slips/itau.php on line 54

Notice: Undefined index: quantity in /home/planeta/public_html/skin/gamuza/slips/itau.php on line 72

Notice: Undefined index: unitary_value in /home/planeta/public_html/skin/gamuza/slips/itau.php on line 73

Notice: Undefined variable: identification in /home/planeta/public_html/skin/gamuza/slips/itau.php on line 92

Notice: Undefined index: company_taxvat in /home/planeta/public_html/skin/gamuza/slips/itau.php on line 93

Notice: Undefined index: company_city_region in /home/planeta/public_html/skin/gamuza/slips/itau.php on line 95

Notice: Undefined index: analytics in /home/planeta/public_html/skin/gamuza/slips/include/layout_itau.php on line 273
================================

Em anexo o boleto com erro...

Poderia me ajudar a resolver este erro por gentileza?

No aguardo, obrigado!

[boleto_com_erro_gamuza.pdf](https://github.com/gamuzatech/gamuza_slips-magento/files/1989602/boleto_com_erro_gamuza.pdf)

**Comment by eneiasramos** [comment]
Olá @grupouweb ! Tudo bem?

Por favor, verifique se a sua variável do PHP **display_errors** está setada como **0** no seu arquivo **index.php**

ini_set('display_errors', 0);

Att,
